# Generated by Django 5.0 on 2023-12-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('desarrollador', models.CharField(max_length=50)),
                ('distribuidor', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
